import "./globals.css";
import Navbar from './Navbar/Navbar';
import { Toaster } from 'sonner';

export const metadata = {
  title: "Telegram Scheduler",
  description: "Generated by Raghavan R",
  icons: {
    icon: '/favicon.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Toaster position="top-center" richColors expand /> 
        <Navbar/>
        {children}
        
      </body>
    </html>
  );
}
